version: '3.8'
services:
#  app:
#    image: laravelphp/php-fpm
#    container_name: laravel_app
#    working_dir: /var/www/html
#    volumes:
#      - ./:/var/www
#    depends_on:
#      - db
#
#  web:
#    image: nginx:alpine
#    container_name: laravel_web
#    ports:
#      - "8000:80"
#    volumes:
#      - ./:/var/www
#      - ./nginx/conf.d:/etc/nginx/conf.d
#    depends_on:
#      - app

  db:
    image: mysql:8
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_DATABASE: twoj_startup
      MYSQL_ROOT_PASSWORD: twoj_startup_secret123
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
